### ISSUE TITLE
Question: Where to find final results?

### ISSUE THREAD

**Issue by olgamie** [ApaBila/NNbenchmarkArticle#1]
Hi!
Your project looks very impressing! I'm interested in the final results of all the packages evaluation. Are they already available? If so, would be so kind and point where I can find them.
Many thanks!

**Comment by ApaBila** [comment]
Hi!
So sorry for the very late response. I somehow missed the notification.
This year's GSoC we're consolidating the results with some additions (code & packages).
We hope to finalize the results by the time the program has finished (end of August), though the results might be modified to be publishable. I'm going to continue updating my work on the article on this repo as long as it is okay with my mentor. You can watch the repo to stay updated, if you want to.

You're welcome!

--
Bila
